"""add role to user

Revision ID: 754ba5dba5a4
Revises: 9326f25a82f2
Create Date: 2026-02-17 14:45:24.437766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '754ba5dba5a4'
down_revision: Union[str, Sequence[str], None] = '9326f25a82f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.add_column('user', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('user', 'role')
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], name=op.f('reviews_book_uid_fkey')),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name=op.f('reviews_user_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('reviews_pkey'))
    )
    # ### end Alembic commands ###
